sudo: require
services:
  - docker

before_install:
  - docker build -t vilusluc/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vilusluc/docker-react npm run test


deploy:
  provider: elasticbeanstalk
  region: "ca-central-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ca-central-1-091342932904"
  bucket_path: "docker_react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"